/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatDto } from '../../models/chat-dto';

export interface UsersUserIdChatsGet$Params {
  userId: string;
}

export function usersUserIdChatsGet(http: HttpClient, rootUrl: string, params: UsersUserIdChatsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatDto>>> {
  const rb = new RequestBuilder(rootUrl, usersUserIdChatsGet.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChatDto>>;
    })
  );
}

usersUserIdChatsGet.PATH = '/users/{userId}/chats';
