/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatDto } from '../../models/chat-dto';
import { CreateChatRequest } from '../../models/create-chat-request';

export interface ChatsPost$Params {
      body?: CreateChatRequest
}

export function chatsPost(http: HttpClient, rootUrl: string, params?: ChatsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatDto>> {
  const rb = new RequestBuilder(rootUrl, chatsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatDto>;
    })
  );
}

chatsPost.PATH = '/chats';
