/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ChatsChatIdPatch$Params {
  chatId: string;
  participantIds?: Array<string>;
}

export function chatsChatIdPatch(http: HttpClient, rootUrl: string, params: ChatsChatIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, chatsChatIdPatch.PATH, 'patch');
  if (params) {
    rb.path('chatId', params.chatId, {});
    rb.query('participantIds', params.participantIds, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

chatsChatIdPatch.PATH = '/chats/{chatId}';
