/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthorizationResponse } from '../../models/authorization-response';
import { LoginRequest } from '../../models/login-request';

export interface AuthorizationLoginPost$Json$Params {
      body?: LoginRequest
}

export function authorizationLoginPost$Json(http: HttpClient, rootUrl: string, params?: AuthorizationLoginPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthorizationResponse>> {
  const rb = new RequestBuilder(rootUrl, authorizationLoginPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthorizationResponse>;
    })
  );
}

authorizationLoginPost$Json.PATH = '/authorization/login';
