/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface AuthorizationResponse {
  token?: string | null;
  user?: UserDto;
}
