/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageDto } from '../models/message-dto';
import { UserDto } from '../models/user-dto';
export interface ChatDto {
  isGroup?: boolean;
  messages?: Array<MessageDto> | null;
  participants?: Array<UserDto> | null;
  title?: string | null;
}
