/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface CommentDto {
  id?: string;
  createdAt?: string;
  createdBy?: UserDto;
  text?: string | null;
}
