/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateChatRequest {
  isGroup?: boolean;
  participantIds?: Array<string> | null;
  title?: string | null;
}
