/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  birthDate?: string;
  firstName?: string | null;
  lastName?: string | null;
  password?: string | null;
  username?: string | null;
}
