/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageDto } from '../models/image-dto';
import { UserDto } from '../models/user-dto';
export interface MessageDto {
  id?: string;
  bodyHtml?: string | null;
  createdAt?: string;
  createdBy?: UserDto;
  images?: Array<ImageDto> | null;
}
