/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentDto } from '../models/comment-dto';
import { ImageDto } from '../models/image-dto';
import { LikeDto } from '../models/like-dto';
import { UserDto } from '../models/user-dto';
export interface PostDto {
  bodyHtml?: string | null;
  comments?: Array<CommentDto> | null;
  createdAt?: string;
  createdBy?: UserDto;
  id?: string;
  images?: Array<ImageDto> | null;
  likes?: Array<LikeDto> | null;
  title?: string | null;
}
