/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSettingsDto } from '../models/user-settings-dto';
export interface UserDto {
  birthDate?: string;
  firstName?: string | null;
  id?: string;
  lastLogin?: string;
  lastName?: string | null;
  userSettings?: UserSettingsDto;
  username?: string | null;
}
